package be.angelcorp.sofa;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : sofa-platform\src\main\cpp\src\sofam.h:25</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("sofa") 
public class iauLDBODY extends StructObject {
	public iauLDBODY() {
		super();
	}
	/// mass of the body (solar masses)
	@Field(0) 
	public double bm() {
		return this.io.getDoubleField(this, 0);
	}
	/// mass of the body (solar masses)
	@Field(0) 
	public iauLDBODY bm(double bm) {
		this.io.setDoubleField(this, 0, bm);
		return this;
	}
	/// deflection limiter (radians^2/2)
	@Field(1) 
	public double dl() {
		return this.io.getDoubleField(this, 1);
	}
	/// deflection limiter (radians^2/2)
	@Field(1) 
	public iauLDBODY dl(double dl) {
		this.io.setDoubleField(this, 1, dl);
		return this;
	}
	/**
	 * barycentric PV of the body (au, au/day)<br>
	 * C type : double[2][3]
	 */
	@Array({2, 3}) 
	@Field(2) 
	public Pointer<Double > pv() {
		return this.io.getPointerField(this, 2);
	}
	public iauLDBODY(Pointer pointer) {
		super(pointer);
	}
}
