package be.angelcorp.sofa;
import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>sofa</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("sofa") 
@Runtime(CRuntime.class) 
public class SofaLibrary {
	static {
		BridJ.register();
	}
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final int WGS72 = (int)3;
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DAS2R = (double)(4.848136811095359935899141e-6);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJM = (double)(365250.0);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DAU = (double)(149597870e3);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double TTMTAI = (double)(32.184);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJY = (double)(365.25);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJM77 = (double)(43144.0);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final int WGS84 = (int)1;
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DPI = (double)(3.141592653589793238462643);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DD2R = (double)(1.745329251994329576923691e-2);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double D2PI = (double)(6.283185307179586476925287);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double ELB = (double)(1.550519768e-8);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJM0 = (double)(2400000.5);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DS2R = (double)(7.272205216643039903848712e-5);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double ELG = (double)(6.969290134e-10);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double TDB0 = (double)(-6.55e-5);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double TURNAS = (double)(1296000.0);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DTY = (double)(365.242198781);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DAYSEC = (double)(86400.0);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DC = (double)((86400.0) / 499.004782);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJM00 = (double)(51544.5);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DR2AS = (double)(206264.8062470963551564734);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final int GRS80 = (int)2;
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DMAS2R = (double)((4.848136811095359935899141e-6) / 1e3);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJ00 = (double)(2451545.0);
	/// <i>native declaration : src\main\cpp\sofa\src\sofam.h</i>
	public static final double DJC = (double)(36525.0);
	/**
	 * Astronomy/Calendars<br>
	 * Original signature : <code>int iauCal2jd(int, int, int, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:4</i>
	 */
	public static int iauCal2jd(int iy, int im, int id, Pointer<Double > djm0, Pointer<Double > djm) {
		return iauCal2jd(iy, im, id, Pointer.getPeer(djm0), Pointer.getPeer(djm));
	}
	protected native static int iauCal2jd(int iy, int im, int id, @Ptr long djm0, @Ptr long djm);
	/**
	 * Original signature : <code>double iauEpb(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:6</i>
	 */
	native public static double iauEpb(double dj1, double dj2);
	/**
	 * Original signature : <code>void iauEpb2jd(double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:8</i>
	 */
	public static void iauEpb2jd(double epb, Pointer<Double > djm0, Pointer<Double > djm) {
		iauEpb2jd(epb, Pointer.getPeer(djm0), Pointer.getPeer(djm));
	}
	protected native static void iauEpb2jd(double epb, @Ptr long djm0, @Ptr long djm);
	/**
	 * Original signature : <code>double iauEpj(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:10</i>
	 */
	native public static double iauEpj(double dj1, double dj2);
	/**
	 * Original signature : <code>void iauEpj2jd(double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:12</i>
	 */
	public static void iauEpj2jd(double epj, Pointer<Double > djm0, Pointer<Double > djm) {
		iauEpj2jd(epj, Pointer.getPeer(djm0), Pointer.getPeer(djm));
	}
	protected native static void iauEpj2jd(double epj, @Ptr long djm0, @Ptr long djm);
	/**
	 * Original signature : <code>int iauJd2cal(double, double, int*, int*, int*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:14</i>
	 */
	public static int iauJd2cal(double dj1, double dj2, Pointer<Integer > iy, Pointer<Integer > im, Pointer<Integer > id, Pointer<Double > fd) {
		return iauJd2cal(dj1, dj2, Pointer.getPeer(iy), Pointer.getPeer(im), Pointer.getPeer(id), Pointer.getPeer(fd));
	}
	protected native static int iauJd2cal(double dj1, double dj2, @Ptr long iy, @Ptr long im, @Ptr long id, @Ptr long fd);
	/**
	 * Original signature : <code>int iauJdcalf(int, double, double, int[4])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:16</i>
	 */
	public static int iauJdcalf(int ndp, double dj1, double dj2, Pointer<Integer > iymdf) {
		return iauJdcalf(ndp, dj1, dj2, Pointer.getPeer(iymdf));
	}
	protected native static int iauJdcalf(int ndp, double dj1, double dj2, @Ptr long iymdf);
	/**
	 * Astronomy/Ephemerides<br>
	 * Original signature : <code>int iauEpv00(double, double, double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:21</i>
	 */
	public static int iauEpv00(double date1, double date2, Pointer<Double > pvh, Pointer<Double > pvb) {
		return iauEpv00(date1, date2, Pointer.getPeer(pvh), Pointer.getPeer(pvb));
	}
	protected native static int iauEpv00(double date1, double date2, @Ptr long pvh, @Ptr long pvb);
	/**
	 * Original signature : <code>int iauPlan94(double, double, int, double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:23</i>
	 */
	public static int iauPlan94(double date1, double date2, int np, Pointer<Double > pv) {
		return iauPlan94(date1, date2, np, Pointer.getPeer(pv));
	}
	protected native static int iauPlan94(double date1, double date2, int np, @Ptr long pv);
	/**
	 * Astronomy/FundamentalArgs<br>
	 * Original signature : <code>double iauFad03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:28</i>
	 */
	native public static double iauFad03(double t);
	/**
	 * Original signature : <code>double iauFae03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:30</i>
	 */
	native public static double iauFae03(double t);
	/**
	 * Original signature : <code>double iauFaf03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:32</i>
	 */
	native public static double iauFaf03(double t);
	/**
	 * Original signature : <code>double iauFaju03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:34</i>
	 */
	native public static double iauFaju03(double t);
	/**
	 * Original signature : <code>double iauFal03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:36</i>
	 */
	native public static double iauFal03(double t);
	/**
	 * Original signature : <code>double iauFalp03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:38</i>
	 */
	native public static double iauFalp03(double t);
	/**
	 * Original signature : <code>double iauFama03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:40</i>
	 */
	native public static double iauFama03(double t);
	/**
	 * Original signature : <code>double iauFame03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:42</i>
	 */
	native public static double iauFame03(double t);
	/**
	 * Original signature : <code>double iauFane03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:44</i>
	 */
	native public static double iauFane03(double t);
	/**
	 * Original signature : <code>double iauFaom03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:46</i>
	 */
	native public static double iauFaom03(double t);
	/**
	 * Original signature : <code>double iauFapa03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:48</i>
	 */
	native public static double iauFapa03(double t);
	/**
	 * Original signature : <code>double iauFasa03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:50</i>
	 */
	native public static double iauFasa03(double t);
	/**
	 * Original signature : <code>double iauFaur03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:52</i>
	 */
	native public static double iauFaur03(double t);
	/**
	 * Original signature : <code>double iauFave03(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:54</i>
	 */
	native public static double iauFave03(double t);
	/**
	 * Astronomy/PrecNutPolar<br>
	 * Original signature : <code>void iauBi00(double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:59</i>
	 */
	public static void iauBi00(Pointer<Double > dpsibi, Pointer<Double > depsbi, Pointer<Double > dra) {
		iauBi00(Pointer.getPeer(dpsibi), Pointer.getPeer(depsbi), Pointer.getPeer(dra));
	}
	protected native static void iauBi00(@Ptr long dpsibi, @Ptr long depsbi, @Ptr long dra);
	/**
	 * Original signature : <code>void iauBp00(double, double, double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:61</i>
	 */
	public static void iauBp00(double date1, double date2, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp) {
		iauBp00(date1, date2, Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp));
	}
	protected native static void iauBp00(double date1, double date2, @Ptr long rb, @Ptr long rp, @Ptr long rbp);
	/**
	 * Original signature : <code>void iauBp06(double, double, double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:63</i>
	 */
	public static void iauBp06(double date1, double date2, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp) {
		iauBp06(date1, date2, Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp));
	}
	protected native static void iauBp06(double date1, double date2, @Ptr long rb, @Ptr long rp, @Ptr long rbp);
	/**
	 * Original signature : <code>void iauBpn2xy(double[3][3], double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:65</i>
	 */
	public static void iauBpn2xy(Pointer<Double > rbpn, Pointer<Double > x, Pointer<Double > y) {
		iauBpn2xy(Pointer.getPeer(rbpn), Pointer.getPeer(x), Pointer.getPeer(y));
	}
	protected native static void iauBpn2xy(@Ptr long rbpn, @Ptr long x, @Ptr long y);
	/**
	 * Original signature : <code>void iauC2i00a(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:67</i>
	 */
	public static void iauC2i00a(double date1, double date2, Pointer<Double > rc2i) {
		iauC2i00a(date1, date2, Pointer.getPeer(rc2i));
	}
	protected native static void iauC2i00a(double date1, double date2, @Ptr long rc2i);
	/**
	 * Original signature : <code>void iauC2i00b(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:69</i>
	 */
	public static void iauC2i00b(double date1, double date2, Pointer<Double > rc2i) {
		iauC2i00b(date1, date2, Pointer.getPeer(rc2i));
	}
	protected native static void iauC2i00b(double date1, double date2, @Ptr long rc2i);
	/**
	 * Original signature : <code>void iauC2i06a(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:71</i>
	 */
	public static void iauC2i06a(double date1, double date2, Pointer<Double > rc2i) {
		iauC2i06a(date1, date2, Pointer.getPeer(rc2i));
	}
	protected native static void iauC2i06a(double date1, double date2, @Ptr long rc2i);
	/**
	 * Original signature : <code>void iauC2ibpn(double, double, double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:73</i>
	 */
	public static void iauC2ibpn(double date1, double date2, Pointer<Double > rbpn, Pointer<Double > rc2i) {
		iauC2ibpn(date1, date2, Pointer.getPeer(rbpn), Pointer.getPeer(rc2i));
	}
	protected native static void iauC2ibpn(double date1, double date2, @Ptr long rbpn, @Ptr long rc2i);
	/**
	 * Original signature : <code>void iauC2ixy(double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:75</i>
	 */
	public static void iauC2ixy(double date1, double date2, double x, double y, Pointer<Double > rc2i) {
		iauC2ixy(date1, date2, x, y, Pointer.getPeer(rc2i));
	}
	protected native static void iauC2ixy(double date1, double date2, double x, double y, @Ptr long rc2i);
	/**
	 * Original signature : <code>void iauC2ixys(double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:77</i>
	 */
	public static void iauC2ixys(double x, double y, double s, Pointer<Double > rc2i) {
		iauC2ixys(x, y, s, Pointer.getPeer(rc2i));
	}
	protected native static void iauC2ixys(double x, double y, double s, @Ptr long rc2i);
	/**
	 * Original signature : <code>void iauC2t00a(double, double, double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:79</i>
	 */
	public static void iauC2t00a(double tta, double ttb, double uta, double utb, double xp, double yp, Pointer<Double > rc2t) {
		iauC2t00a(tta, ttb, uta, utb, xp, yp, Pointer.getPeer(rc2t));
	}
	protected native static void iauC2t00a(double tta, double ttb, double uta, double utb, double xp, double yp, @Ptr long rc2t);
	/**
	 * Original signature : <code>void iauC2t00b(double, double, double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:81</i>
	 */
	public static void iauC2t00b(double tta, double ttb, double uta, double utb, double xp, double yp, Pointer<Double > rc2t) {
		iauC2t00b(tta, ttb, uta, utb, xp, yp, Pointer.getPeer(rc2t));
	}
	protected native static void iauC2t00b(double tta, double ttb, double uta, double utb, double xp, double yp, @Ptr long rc2t);
	/**
	 * Original signature : <code>void iauC2t06a(double, double, double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:83</i>
	 */
	public static void iauC2t06a(double tta, double ttb, double uta, double utb, double xp, double yp, Pointer<Double > rc2t) {
		iauC2t06a(tta, ttb, uta, utb, xp, yp, Pointer.getPeer(rc2t));
	}
	protected native static void iauC2t06a(double tta, double ttb, double uta, double utb, double xp, double yp, @Ptr long rc2t);
	/**
	 * Original signature : <code>void iauC2tcio(double[3][3], double, double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:85</i>
	 */
	public static void iauC2tcio(Pointer<Double > rc2i, double era, Pointer<Double > rpom, Pointer<Double > rc2t) {
		iauC2tcio(Pointer.getPeer(rc2i), era, Pointer.getPeer(rpom), Pointer.getPeer(rc2t));
	}
	protected native static void iauC2tcio(@Ptr long rc2i, double era, @Ptr long rpom, @Ptr long rc2t);
	/**
	 * Original signature : <code>void iauC2teqx(double[3][3], double, double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:87</i>
	 */
	public static void iauC2teqx(Pointer<Double > rbpn, double gst, Pointer<Double > rpom, Pointer<Double > rc2t) {
		iauC2teqx(Pointer.getPeer(rbpn), gst, Pointer.getPeer(rpom), Pointer.getPeer(rc2t));
	}
	protected native static void iauC2teqx(@Ptr long rbpn, double gst, @Ptr long rpom, @Ptr long rc2t);
	/**
	 * Original signature : <code>void iauC2tpe(double, double, double, double, double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:89</i>
	 */
	public static void iauC2tpe(double tta, double ttb, double uta, double utb, double dpsi, double deps, double xp, double yp, Pointer<Double > rc2t) {
		iauC2tpe(tta, ttb, uta, utb, dpsi, deps, xp, yp, Pointer.getPeer(rc2t));
	}
	protected native static void iauC2tpe(double tta, double ttb, double uta, double utb, double dpsi, double deps, double xp, double yp, @Ptr long rc2t);
	/**
	 * Original signature : <code>void iauC2txy(double, double, double, double, double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:91</i>
	 */
	public static void iauC2txy(double tta, double ttb, double uta, double utb, double x, double y, double xp, double yp, Pointer<Double > rc2t) {
		iauC2txy(tta, ttb, uta, utb, x, y, xp, yp, Pointer.getPeer(rc2t));
	}
	protected native static void iauC2txy(double tta, double ttb, double uta, double utb, double x, double y, double xp, double yp, @Ptr long rc2t);
	/**
	 * Original signature : <code>double iauEo06a(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:93</i>
	 */
	native public static double iauEo06a(double date1, double date2);
	/**
	 * Original signature : <code>double iauEors(double[3][3], double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:95</i>
	 */
	public static double iauEors(Pointer<Double > rnpb, double s) {
		return iauEors(Pointer.getPeer(rnpb), s);
	}
	protected native static double iauEors(@Ptr long rnpb, double s);
	/**
	 * Original signature : <code>void iauFw2m(double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:97</i>
	 */
	public static void iauFw2m(double gamb, double phib, double psi, double eps, Pointer<Double > r) {
		iauFw2m(gamb, phib, psi, eps, Pointer.getPeer(r));
	}
	protected native static void iauFw2m(double gamb, double phib, double psi, double eps, @Ptr long r);
	/**
	 * Original signature : <code>void iauFw2xy(double, double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:99</i>
	 */
	public static void iauFw2xy(double gamb, double phib, double psi, double eps, Pointer<Double > x, Pointer<Double > y) {
		iauFw2xy(gamb, phib, psi, eps, Pointer.getPeer(x), Pointer.getPeer(y));
	}
	protected native static void iauFw2xy(double gamb, double phib, double psi, double eps, @Ptr long x, @Ptr long y);
	/**
	 * Original signature : <code>void iauNum00a(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:101</i>
	 */
	public static void iauNum00a(double date1, double date2, Pointer<Double > rmatn) {
		iauNum00a(date1, date2, Pointer.getPeer(rmatn));
	}
	protected native static void iauNum00a(double date1, double date2, @Ptr long rmatn);
	/**
	 * Original signature : <code>void iauNum00b(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:103</i>
	 */
	public static void iauNum00b(double date1, double date2, Pointer<Double > rmatn) {
		iauNum00b(date1, date2, Pointer.getPeer(rmatn));
	}
	protected native static void iauNum00b(double date1, double date2, @Ptr long rmatn);
	/**
	 * Original signature : <code>void iauNum06a(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:105</i>
	 */
	public static void iauNum06a(double date1, double date2, Pointer<Double > rmatn) {
		iauNum06a(date1, date2, Pointer.getPeer(rmatn));
	}
	protected native static void iauNum06a(double date1, double date2, @Ptr long rmatn);
	/**
	 * Original signature : <code>void iauNumat(double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:107</i>
	 */
	public static void iauNumat(double epsa, double dpsi, double deps, Pointer<Double > rmatn) {
		iauNumat(epsa, dpsi, deps, Pointer.getPeer(rmatn));
	}
	protected native static void iauNumat(double epsa, double dpsi, double deps, @Ptr long rmatn);
	/**
	 * Original signature : <code>void iauNut00a(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:109</i>
	 */
	public static void iauNut00a(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps) {
		iauNut00a(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps));
	}
	protected native static void iauNut00a(double date1, double date2, @Ptr long dpsi, @Ptr long deps);
	/**
	 * Original signature : <code>void iauNut00b(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:111</i>
	 */
	public static void iauNut00b(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps) {
		iauNut00b(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps));
	}
	protected native static void iauNut00b(double date1, double date2, @Ptr long dpsi, @Ptr long deps);
	/**
	 * Original signature : <code>void iauNut06a(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:113</i>
	 */
	public static void iauNut06a(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps) {
		iauNut06a(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps));
	}
	protected native static void iauNut06a(double date1, double date2, @Ptr long dpsi, @Ptr long deps);
	/**
	 * Original signature : <code>void iauNut80(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:115</i>
	 */
	public static void iauNut80(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps) {
		iauNut80(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps));
	}
	protected native static void iauNut80(double date1, double date2, @Ptr long dpsi, @Ptr long deps);
	/**
	 * Original signature : <code>void iauNutm80(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:117</i>
	 */
	public static void iauNutm80(double date1, double date2, Pointer<Double > rmatn) {
		iauNutm80(date1, date2, Pointer.getPeer(rmatn));
	}
	protected native static void iauNutm80(double date1, double date2, @Ptr long rmatn);
	/**
	 * Original signature : <code>double iauObl06(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:119</i>
	 */
	native public static double iauObl06(double date1, double date2);
	/**
	 * Original signature : <code>double iauObl80(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:121</i>
	 */
	native public static double iauObl80(double date1, double date2);
	/**
	 * Original signature : <code>void iauP06e(double, double, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:123</i>
	 */
	public static void iauP06e(double date1, double date2, Pointer<Double > eps0, Pointer<Double > psia, Pointer<Double > oma, Pointer<Double > bpa, Pointer<Double > bqa, Pointer<Double > pia, Pointer<Double > bpia, Pointer<Double > epsa, Pointer<Double > chia, Pointer<Double > za, Pointer<Double > zetaa, Pointer<Double > thetaa, Pointer<Double > pa, Pointer<Double > gam, Pointer<Double > phi, Pointer<Double > psi) {
		iauP06e(date1, date2, Pointer.getPeer(eps0), Pointer.getPeer(psia), Pointer.getPeer(oma), Pointer.getPeer(bpa), Pointer.getPeer(bqa), Pointer.getPeer(pia), Pointer.getPeer(bpia), Pointer.getPeer(epsa), Pointer.getPeer(chia), Pointer.getPeer(za), Pointer.getPeer(zetaa), Pointer.getPeer(thetaa), Pointer.getPeer(pa), Pointer.getPeer(gam), Pointer.getPeer(phi), Pointer.getPeer(psi));
	}
	protected native static void iauP06e(double date1, double date2, @Ptr long eps0, @Ptr long psia, @Ptr long oma, @Ptr long bpa, @Ptr long bqa, @Ptr long pia, @Ptr long bpia, @Ptr long epsa, @Ptr long chia, @Ptr long za, @Ptr long zetaa, @Ptr long thetaa, @Ptr long pa, @Ptr long gam, @Ptr long phi, @Ptr long psi);
	/**
	 * Original signature : <code>void iauPb06(double, double, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:125</i>
	 */
	public static void iauPb06(double date1, double date2, Pointer<Double > bzeta, Pointer<Double > bz, Pointer<Double > btheta) {
		iauPb06(date1, date2, Pointer.getPeer(bzeta), Pointer.getPeer(bz), Pointer.getPeer(btheta));
	}
	protected native static void iauPb06(double date1, double date2, @Ptr long bzeta, @Ptr long bz, @Ptr long btheta);
	/**
	 * Original signature : <code>void iauPfw06(double, double, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:127</i>
	 */
	public static void iauPfw06(double date1, double date2, Pointer<Double > gamb, Pointer<Double > phib, Pointer<Double > psib, Pointer<Double > epsa) {
		iauPfw06(date1, date2, Pointer.getPeer(gamb), Pointer.getPeer(phib), Pointer.getPeer(psib), Pointer.getPeer(epsa));
	}
	protected native static void iauPfw06(double date1, double date2, @Ptr long gamb, @Ptr long phib, @Ptr long psib, @Ptr long epsa);
	/**
	 * Original signature : <code>void iauPmat00(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:129</i>
	 */
	public static void iauPmat00(double date1, double date2, Pointer<Double > rbp) {
		iauPmat00(date1, date2, Pointer.getPeer(rbp));
	}
	protected native static void iauPmat00(double date1, double date2, @Ptr long rbp);
	/**
	 * Original signature : <code>void iauPmat06(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:131</i>
	 */
	public static void iauPmat06(double date1, double date2, Pointer<Double > rbp) {
		iauPmat06(date1, date2, Pointer.getPeer(rbp));
	}
	protected native static void iauPmat06(double date1, double date2, @Ptr long rbp);
	/**
	 * Original signature : <code>void iauPmat76(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:133</i>
	 */
	public static void iauPmat76(double date1, double date2, Pointer<Double > rmatp) {
		iauPmat76(date1, date2, Pointer.getPeer(rmatp));
	}
	protected native static void iauPmat76(double date1, double date2, @Ptr long rmatp);
	/**
	 * Original signature : <code>void iauPn00(double, double, double, double, double*, double[3][3], double[3][3], double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:135</i>
	 */
	public static void iauPn00(double date1, double date2, double dpsi, double deps, Pointer<Double > epsa, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp, Pointer<Double > rn, Pointer<Double > rbpn) {
		iauPn00(date1, date2, dpsi, deps, Pointer.getPeer(epsa), Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp), Pointer.getPeer(rn), Pointer.getPeer(rbpn));
	}
	protected native static void iauPn00(double date1, double date2, double dpsi, double deps, @Ptr long epsa, @Ptr long rb, @Ptr long rp, @Ptr long rbp, @Ptr long rn, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPn00a(double, double, double*, double*, double*, double[3][3], double[3][3], double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:137</i>
	 */
	public static void iauPn00a(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps, Pointer<Double > epsa, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp, Pointer<Double > rn, Pointer<Double > rbpn) {
		iauPn00a(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps), Pointer.getPeer(epsa), Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp), Pointer.getPeer(rn), Pointer.getPeer(rbpn));
	}
	protected native static void iauPn00a(double date1, double date2, @Ptr long dpsi, @Ptr long deps, @Ptr long epsa, @Ptr long rb, @Ptr long rp, @Ptr long rbp, @Ptr long rn, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPn00b(double, double, double*, double*, double*, double[3][3], double[3][3], double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:139</i>
	 */
	public static void iauPn00b(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps, Pointer<Double > epsa, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp, Pointer<Double > rn, Pointer<Double > rbpn) {
		iauPn00b(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps), Pointer.getPeer(epsa), Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp), Pointer.getPeer(rn), Pointer.getPeer(rbpn));
	}
	protected native static void iauPn00b(double date1, double date2, @Ptr long dpsi, @Ptr long deps, @Ptr long epsa, @Ptr long rb, @Ptr long rp, @Ptr long rbp, @Ptr long rn, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPn06(double, double, double, double, double*, double[3][3], double[3][3], double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:141</i>
	 */
	public static void iauPn06(double date1, double date2, double dpsi, double deps, Pointer<Double > epsa, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp, Pointer<Double > rn, Pointer<Double > rbpn) {
		iauPn06(date1, date2, dpsi, deps, Pointer.getPeer(epsa), Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp), Pointer.getPeer(rn), Pointer.getPeer(rbpn));
	}
	protected native static void iauPn06(double date1, double date2, double dpsi, double deps, @Ptr long epsa, @Ptr long rb, @Ptr long rp, @Ptr long rbp, @Ptr long rn, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPn06a(double, double, double*, double*, double*, double[3][3], double[3][3], double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:143</i>
	 */
	public static void iauPn06a(double date1, double date2, Pointer<Double > dpsi, Pointer<Double > deps, Pointer<Double > epsa, Pointer<Double > rb, Pointer<Double > rp, Pointer<Double > rbp, Pointer<Double > rn, Pointer<Double > rbpn) {
		iauPn06a(date1, date2, Pointer.getPeer(dpsi), Pointer.getPeer(deps), Pointer.getPeer(epsa), Pointer.getPeer(rb), Pointer.getPeer(rp), Pointer.getPeer(rbp), Pointer.getPeer(rn), Pointer.getPeer(rbpn));
	}
	protected native static void iauPn06a(double date1, double date2, @Ptr long dpsi, @Ptr long deps, @Ptr long epsa, @Ptr long rb, @Ptr long rp, @Ptr long rbp, @Ptr long rn, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPnm00a(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:145</i>
	 */
	public static void iauPnm00a(double date1, double date2, Pointer<Double > rbpn) {
		iauPnm00a(date1, date2, Pointer.getPeer(rbpn));
	}
	protected native static void iauPnm00a(double date1, double date2, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPnm00b(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:147</i>
	 */
	public static void iauPnm00b(double date1, double date2, Pointer<Double > rbpn) {
		iauPnm00b(date1, date2, Pointer.getPeer(rbpn));
	}
	protected native static void iauPnm00b(double date1, double date2, @Ptr long rbpn);
	/**
	 * Original signature : <code>void iauPnm06a(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:149</i>
	 */
	public static void iauPnm06a(double date1, double date2, Pointer<Double > rnpb) {
		iauPnm06a(date1, date2, Pointer.getPeer(rnpb));
	}
	protected native static void iauPnm06a(double date1, double date2, @Ptr long rnpb);
	/**
	 * Original signature : <code>void iauPnm80(double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:151</i>
	 */
	public static void iauPnm80(double date1, double date2, Pointer<Double > rmatpn) {
		iauPnm80(date1, date2, Pointer.getPeer(rmatpn));
	}
	protected native static void iauPnm80(double date1, double date2, @Ptr long rmatpn);
	/**
	 * Original signature : <code>void iauPom00(double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:153</i>
	 */
	public static void iauPom00(double xp, double yp, double sp, Pointer<Double > rpom) {
		iauPom00(xp, yp, sp, Pointer.getPeer(rpom));
	}
	protected native static void iauPom00(double xp, double yp, double sp, @Ptr long rpom);
	/**
	 * Original signature : <code>void iauPr00(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:155</i>
	 */
	public static void iauPr00(double date1, double date2, Pointer<Double > dpsipr, Pointer<Double > depspr) {
		iauPr00(date1, date2, Pointer.getPeer(dpsipr), Pointer.getPeer(depspr));
	}
	protected native static void iauPr00(double date1, double date2, @Ptr long dpsipr, @Ptr long depspr);
	/**
	 * Original signature : <code>void iauPrec76(double, double, double, double, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:157</i>
	 */
	public static void iauPrec76(double ep01, double ep02, double ep11, double ep12, Pointer<Double > zeta, Pointer<Double > z, Pointer<Double > theta) {
		iauPrec76(ep01, ep02, ep11, ep12, Pointer.getPeer(zeta), Pointer.getPeer(z), Pointer.getPeer(theta));
	}
	protected native static void iauPrec76(double ep01, double ep02, double ep11, double ep12, @Ptr long zeta, @Ptr long z, @Ptr long theta);
	/**
	 * Original signature : <code>double iauS00(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:159</i>
	 */
	native public static double iauS00(double date1, double date2, double x, double y);
	/**
	 * Original signature : <code>double iauS00a(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:161</i>
	 */
	native public static double iauS00a(double date1, double date2);
	/**
	 * Original signature : <code>double iauS00b(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:163</i>
	 */
	native public static double iauS00b(double date1, double date2);
	/**
	 * Original signature : <code>double iauS06(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:165</i>
	 */
	native public static double iauS06(double date1, double date2, double x, double y);
	/**
	 * Original signature : <code>double iauS06a(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:167</i>
	 */
	native public static double iauS06a(double date1, double date2);
	/**
	 * Original signature : <code>double iauSp00(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:169</i>
	 */
	native public static double iauSp00(double date1, double date2);
	/**
	 * Original signature : <code>void iauXy06(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:171</i>
	 */
	public static void iauXy06(double date1, double date2, Pointer<Double > x, Pointer<Double > y) {
		iauXy06(date1, date2, Pointer.getPeer(x), Pointer.getPeer(y));
	}
	protected native static void iauXy06(double date1, double date2, @Ptr long x, @Ptr long y);
	/**
	 * Original signature : <code>void iauXys00a(double, double, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:173</i>
	 */
	public static void iauXys00a(double date1, double date2, Pointer<Double > x, Pointer<Double > y, Pointer<Double > s) {
		iauXys00a(date1, date2, Pointer.getPeer(x), Pointer.getPeer(y), Pointer.getPeer(s));
	}
	protected native static void iauXys00a(double date1, double date2, @Ptr long x, @Ptr long y, @Ptr long s);
	/**
	 * Original signature : <code>void iauXys00b(double, double, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:175</i>
	 */
	public static void iauXys00b(double date1, double date2, Pointer<Double > x, Pointer<Double > y, Pointer<Double > s) {
		iauXys00b(date1, date2, Pointer.getPeer(x), Pointer.getPeer(y), Pointer.getPeer(s));
	}
	protected native static void iauXys00b(double date1, double date2, @Ptr long x, @Ptr long y, @Ptr long s);
	/**
	 * Original signature : <code>void iauXys06a(double, double, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:177</i>
	 */
	public static void iauXys06a(double date1, double date2, Pointer<Double > x, Pointer<Double > y, Pointer<Double > s) {
		iauXys06a(date1, date2, Pointer.getPeer(x), Pointer.getPeer(y), Pointer.getPeer(s));
	}
	protected native static void iauXys06a(double date1, double date2, @Ptr long x, @Ptr long y, @Ptr long s);
	/**
	 * Astronomy/RotationAndTime<br>
	 * Original signature : <code>double iauEe00(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:182</i>
	 */
	native public static double iauEe00(double date1, double date2, double epsa, double dpsi);
	/**
	 * Original signature : <code>double iauEe00a(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:184</i>
	 */
	native public static double iauEe00a(double date1, double date2);
	/**
	 * Original signature : <code>double iauEe00b(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:186</i>
	 */
	native public static double iauEe00b(double date1, double date2);
	/**
	 * Original signature : <code>double iauEe06a(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:188</i>
	 */
	native public static double iauEe06a(double date1, double date2);
	/**
	 * Original signature : <code>double iauEect00(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:190</i>
	 */
	native public static double iauEect00(double date1, double date2);
	/**
	 * Original signature : <code>double iauEqeq94(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:192</i>
	 */
	native public static double iauEqeq94(double date1, double date2);
	/**
	 * Original signature : <code>double iauEra00(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:194</i>
	 */
	native public static double iauEra00(double dj1, double dj2);
	/**
	 * Original signature : <code>double iauGmst00(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:196</i>
	 */
	native public static double iauGmst00(double uta, double utb, double tta, double ttb);
	/**
	 * Original signature : <code>double iauGmst06(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:198</i>
	 */
	native public static double iauGmst06(double uta, double utb, double tta, double ttb);
	/**
	 * Original signature : <code>double iauGmst82(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:200</i>
	 */
	native public static double iauGmst82(double dj1, double dj2);
	/**
	 * Original signature : <code>double iauGst00a(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:202</i>
	 */
	native public static double iauGst00a(double uta, double utb, double tta, double ttb);
	/**
	 * Original signature : <code>double iauGst00b(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:204</i>
	 */
	native public static double iauGst00b(double uta, double utb);
	/**
	 * Original signature : <code>double iauGst06(double, double, double, double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:206</i>
	 */
	public static double iauGst06(double uta, double utb, double tta, double ttb, Pointer<Double > rnpb) {
		return iauGst06(uta, utb, tta, ttb, Pointer.getPeer(rnpb));
	}
	protected native static double iauGst06(double uta, double utb, double tta, double ttb, @Ptr long rnpb);
	/**
	 * Original signature : <code>double iauGst06a(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:208</i>
	 */
	native public static double iauGst06a(double uta, double utb, double tta, double ttb);
	/**
	 * Original signature : <code>double iauGst94(double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:210</i>
	 */
	native public static double iauGst94(double uta, double utb);
	/**
	 * Astronomy/SpaceMotion<br>
	 * Original signature : <code>int iauPvstar(double[2][3], double*, double*, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:215</i>
	 */
	public static int iauPvstar(Pointer<Double > pv, Pointer<Double > ra, Pointer<Double > dec, Pointer<Double > pmr, Pointer<Double > pmd, Pointer<Double > px, Pointer<Double > rv) {
		return iauPvstar(Pointer.getPeer(pv), Pointer.getPeer(ra), Pointer.getPeer(dec), Pointer.getPeer(pmr), Pointer.getPeer(pmd), Pointer.getPeer(px), Pointer.getPeer(rv));
	}
	protected native static int iauPvstar(@Ptr long pv, @Ptr long ra, @Ptr long dec, @Ptr long pmr, @Ptr long pmd, @Ptr long px, @Ptr long rv);
	/**
	 * Original signature : <code>int iauStarpv(double, double, double, double, double, double, double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:217</i>
	 */
	public static int iauStarpv(double ra, double dec, double pmr, double pmd, double px, double rv, Pointer<Double > pv) {
		return iauStarpv(ra, dec, pmr, pmd, px, rv, Pointer.getPeer(pv));
	}
	protected native static int iauStarpv(double ra, double dec, double pmr, double pmd, double px, double rv, @Ptr long pv);
	/**
	 * Astronomy/StarCatalogs<br>
	 * Original signature : <code>void iauFk52h(double, double, double, double, double, double, double*, double*, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:222</i>
	 */
	public static void iauFk52h(double r5, double d5, double dr5, double dd5, double px5, double rv5, Pointer<Double > rh, Pointer<Double > dh, Pointer<Double > drh, Pointer<Double > ddh, Pointer<Double > pxh, Pointer<Double > rvh) {
		iauFk52h(r5, d5, dr5, dd5, px5, rv5, Pointer.getPeer(rh), Pointer.getPeer(dh), Pointer.getPeer(drh), Pointer.getPeer(ddh), Pointer.getPeer(pxh), Pointer.getPeer(rvh));
	}
	protected native static void iauFk52h(double r5, double d5, double dr5, double dd5, double px5, double rv5, @Ptr long rh, @Ptr long dh, @Ptr long drh, @Ptr long ddh, @Ptr long pxh, @Ptr long rvh);
	/**
	 * Original signature : <code>void iauFk5hip(double[3][3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:224</i>
	 */
	public static void iauFk5hip(Pointer<Double > r5h, Pointer<Double > s5h) {
		iauFk5hip(Pointer.getPeer(r5h), Pointer.getPeer(s5h));
	}
	protected native static void iauFk5hip(@Ptr long r5h, @Ptr long s5h);
	/**
	 * Original signature : <code>void iauFk5hz(double, double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:226</i>
	 */
	public static void iauFk5hz(double r5, double d5, double date1, double date2, Pointer<Double > rh, Pointer<Double > dh) {
		iauFk5hz(r5, d5, date1, date2, Pointer.getPeer(rh), Pointer.getPeer(dh));
	}
	protected native static void iauFk5hz(double r5, double d5, double date1, double date2, @Ptr long rh, @Ptr long dh);
	/**
	 * Original signature : <code>void iauH2fk5(double, double, double, double, double, double, double*, double*, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:228</i>
	 */
	public static void iauH2fk5(double rh, double dh, double drh, double ddh, double pxh, double rvh, Pointer<Double > r5, Pointer<Double > d5, Pointer<Double > dr5, Pointer<Double > dd5, Pointer<Double > px5, Pointer<Double > rv5) {
		iauH2fk5(rh, dh, drh, ddh, pxh, rvh, Pointer.getPeer(r5), Pointer.getPeer(d5), Pointer.getPeer(dr5), Pointer.getPeer(dd5), Pointer.getPeer(px5), Pointer.getPeer(rv5));
	}
	protected native static void iauH2fk5(double rh, double dh, double drh, double ddh, double pxh, double rvh, @Ptr long r5, @Ptr long d5, @Ptr long dr5, @Ptr long dd5, @Ptr long px5, @Ptr long rv5);
	/**
	 * Original signature : <code>void iauHfk5z(double, double, double, double, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:230</i>
	 */
	public static void iauHfk5z(double rh, double dh, double date1, double date2, Pointer<Double > r5, Pointer<Double > d5, Pointer<Double > dr5, Pointer<Double > dd5) {
		iauHfk5z(rh, dh, date1, date2, Pointer.getPeer(r5), Pointer.getPeer(d5), Pointer.getPeer(dr5), Pointer.getPeer(dd5));
	}
	protected native static void iauHfk5z(double rh, double dh, double date1, double date2, @Ptr long r5, @Ptr long d5, @Ptr long dr5, @Ptr long dd5);
	/**
	 * Original signature : <code>int iauStarpm(double, double, double, double, double, double, double, double, double, double, double*, double*, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:232</i>
	 */
	public static int iauStarpm(double ra1, double dec1, double pmr1, double pmd1, double px1, double rv1, double ep1a, double ep1b, double ep2a, double ep2b, Pointer<Double > ra2, Pointer<Double > dec2, Pointer<Double > pmr2, Pointer<Double > pmd2, Pointer<Double > px2, Pointer<Double > rv2) {
		return iauStarpm(ra1, dec1, pmr1, pmd1, px1, rv1, ep1a, ep1b, ep2a, ep2b, Pointer.getPeer(ra2), Pointer.getPeer(dec2), Pointer.getPeer(pmr2), Pointer.getPeer(pmd2), Pointer.getPeer(px2), Pointer.getPeer(rv2));
	}
	protected native static int iauStarpm(double ra1, double dec1, double pmr1, double pmd1, double px1, double rv1, double ep1a, double ep1b, double ep2a, double ep2b, @Ptr long ra2, @Ptr long dec2, @Ptr long pmr2, @Ptr long pmd2, @Ptr long px2, @Ptr long rv2);
	/**
	 * Astronomy/Geodetic/Geocentric<br>
	 * Original signature : <code>int iauEform(int, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:237</i>
	 */
	public static int iauEform(int n, Pointer<Double > a, Pointer<Double > f) {
		return iauEform(n, Pointer.getPeer(a), Pointer.getPeer(f));
	}
	protected native static int iauEform(int n, @Ptr long a, @Ptr long f);
	/**
	 * Original signature : <code>int iauGc2gd(int, double[3], double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:239</i>
	 */
	public static int iauGc2gd(int n, Pointer<Double > xyz, Pointer<Double > elong, Pointer<Double > phi, Pointer<Double > height) {
		return iauGc2gd(n, Pointer.getPeer(xyz), Pointer.getPeer(elong), Pointer.getPeer(phi), Pointer.getPeer(height));
	}
	protected native static int iauGc2gd(int n, @Ptr long xyz, @Ptr long elong, @Ptr long phi, @Ptr long height);
	/**
	 * Original signature : <code>int iauGc2gde(double, double, double[3], double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:241</i>
	 */
	public static int iauGc2gde(double a, double f, Pointer<Double > xyz, Pointer<Double > elong, Pointer<Double > phi, Pointer<Double > height) {
		return iauGc2gde(a, f, Pointer.getPeer(xyz), Pointer.getPeer(elong), Pointer.getPeer(phi), Pointer.getPeer(height));
	}
	protected native static int iauGc2gde(double a, double f, @Ptr long xyz, @Ptr long elong, @Ptr long phi, @Ptr long height);
	/**
	 * Original signature : <code>int iauGd2gc(int, double, double, double, double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:243</i>
	 */
	public static int iauGd2gc(int n, double elong, double phi, double height, Pointer<Double > xyz) {
		return iauGd2gc(n, elong, phi, height, Pointer.getPeer(xyz));
	}
	protected native static int iauGd2gc(int n, double elong, double phi, double height, @Ptr long xyz);
	/**
	 * Original signature : <code>int iauGd2gce(double, double, double, double, double, double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:245</i>
	 */
	public static int iauGd2gce(double a, double f, double elong, double phi, double height, Pointer<Double > xyz) {
		return iauGd2gce(a, f, elong, phi, height, Pointer.getPeer(xyz));
	}
	protected native static int iauGd2gce(double a, double f, double elong, double phi, double height, @Ptr long xyz);
	/**
	 * Astronomy/Timescales<br>
	 * Original signature : <code>int iauD2dtf(const char*, int, double, double, int*, int*, int*, int[4])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:250</i>
	 */
	public static int iauD2dtf(Pointer<Byte > scale, int ndp, double d1, double d2, Pointer<Integer > iy, Pointer<Integer > im, Pointer<Integer > id, Pointer<Integer > ihmsf) {
		return iauD2dtf(Pointer.getPeer(scale), ndp, d1, d2, Pointer.getPeer(iy), Pointer.getPeer(im), Pointer.getPeer(id), Pointer.getPeer(ihmsf));
	}
	protected native static int iauD2dtf(@Ptr long scale, int ndp, double d1, double d2, @Ptr long iy, @Ptr long im, @Ptr long id, @Ptr long ihmsf);
	/**
	 * Original signature : <code>int iauDat(int, int, int, double, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:252</i>
	 */
	public static int iauDat(int iy, int im, int id, double fd, Pointer<Double > deltat) {
		return iauDat(iy, im, id, fd, Pointer.getPeer(deltat));
	}
	protected native static int iauDat(int iy, int im, int id, double fd, @Ptr long deltat);
	/**
	 * Original signature : <code>double iauDtdb(double, double, double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:254</i>
	 */
	native public static double iauDtdb(double date1, double date2, double ut, double elong, double u, double v);
	/**
	 * Original signature : <code>int iauDtf2d(const char*, int, int, int, int, int, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:256</i>
	 */
	public static int iauDtf2d(Pointer<Byte > scale, int iy, int im, int id, int ihr, int imn, double sec, Pointer<Double > d1, Pointer<Double > d2) {
		return iauDtf2d(Pointer.getPeer(scale), iy, im, id, ihr, imn, sec, Pointer.getPeer(d1), Pointer.getPeer(d2));
	}
	protected native static int iauDtf2d(@Ptr long scale, int iy, int im, int id, int ihr, int imn, double sec, @Ptr long d1, @Ptr long d2);
	/**
	 * Original signature : <code>int iauTaitt(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:258</i>
	 */
	public static int iauTaitt(double tai1, double tai2, Pointer<Double > tt1, Pointer<Double > tt2) {
		return iauTaitt(tai1, tai2, Pointer.getPeer(tt1), Pointer.getPeer(tt2));
	}
	protected native static int iauTaitt(double tai1, double tai2, @Ptr long tt1, @Ptr long tt2);
	/**
	 * Original signature : <code>int iauTaiut1(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:260</i>
	 */
	public static int iauTaiut1(double tai1, double tai2, double dta, Pointer<Double > ut11, Pointer<Double > ut12) {
		return iauTaiut1(tai1, tai2, dta, Pointer.getPeer(ut11), Pointer.getPeer(ut12));
	}
	protected native static int iauTaiut1(double tai1, double tai2, double dta, @Ptr long ut11, @Ptr long ut12);
	/**
	 * Original signature : <code>int iauTaiutc(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:262</i>
	 */
	public static int iauTaiutc(double tai1, double tai2, Pointer<Double > utc1, Pointer<Double > utc2) {
		return iauTaiutc(tai1, tai2, Pointer.getPeer(utc1), Pointer.getPeer(utc2));
	}
	protected native static int iauTaiutc(double tai1, double tai2, @Ptr long utc1, @Ptr long utc2);
	/**
	 * Original signature : <code>int iauTcbtdb(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:264</i>
	 */
	public static int iauTcbtdb(double tcb1, double tcb2, Pointer<Double > tdb1, Pointer<Double > tdb2) {
		return iauTcbtdb(tcb1, tcb2, Pointer.getPeer(tdb1), Pointer.getPeer(tdb2));
	}
	protected native static int iauTcbtdb(double tcb1, double tcb2, @Ptr long tdb1, @Ptr long tdb2);
	/**
	 * Original signature : <code>int iauTcgtt(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:266</i>
	 */
	public static int iauTcgtt(double tcg1, double tcg2, Pointer<Double > tt1, Pointer<Double > tt2) {
		return iauTcgtt(tcg1, tcg2, Pointer.getPeer(tt1), Pointer.getPeer(tt2));
	}
	protected native static int iauTcgtt(double tcg1, double tcg2, @Ptr long tt1, @Ptr long tt2);
	/**
	 * Original signature : <code>int iauTdbtcb(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:268</i>
	 */
	public static int iauTdbtcb(double tdb1, double tdb2, Pointer<Double > tcb1, Pointer<Double > tcb2) {
		return iauTdbtcb(tdb1, tdb2, Pointer.getPeer(tcb1), Pointer.getPeer(tcb2));
	}
	protected native static int iauTdbtcb(double tdb1, double tdb2, @Ptr long tcb1, @Ptr long tcb2);
	/**
	 * Original signature : <code>int iauTdbtt(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:270</i>
	 */
	public static int iauTdbtt(double tdb1, double tdb2, double dtr, Pointer<Double > tt1, Pointer<Double > tt2) {
		return iauTdbtt(tdb1, tdb2, dtr, Pointer.getPeer(tt1), Pointer.getPeer(tt2));
	}
	protected native static int iauTdbtt(double tdb1, double tdb2, double dtr, @Ptr long tt1, @Ptr long tt2);
	/**
	 * Original signature : <code>int iauTttai(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:272</i>
	 */
	public static int iauTttai(double tt1, double tt2, Pointer<Double > tai1, Pointer<Double > tai2) {
		return iauTttai(tt1, tt2, Pointer.getPeer(tai1), Pointer.getPeer(tai2));
	}
	protected native static int iauTttai(double tt1, double tt2, @Ptr long tai1, @Ptr long tai2);
	/**
	 * Original signature : <code>int iauTttcg(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:274</i>
	 */
	public static int iauTttcg(double tt1, double tt2, Pointer<Double > tcg1, Pointer<Double > tcg2) {
		return iauTttcg(tt1, tt2, Pointer.getPeer(tcg1), Pointer.getPeer(tcg2));
	}
	protected native static int iauTttcg(double tt1, double tt2, @Ptr long tcg1, @Ptr long tcg2);
	/**
	 * Original signature : <code>int iauTttdb(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:276</i>
	 */
	public static int iauTttdb(double tt1, double tt2, double dtr, Pointer<Double > tdb1, Pointer<Double > tdb2) {
		return iauTttdb(tt1, tt2, dtr, Pointer.getPeer(tdb1), Pointer.getPeer(tdb2));
	}
	protected native static int iauTttdb(double tt1, double tt2, double dtr, @Ptr long tdb1, @Ptr long tdb2);
	/**
	 * Original signature : <code>int iauTtut1(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:278</i>
	 */
	public static int iauTtut1(double tt1, double tt2, double dt, Pointer<Double > ut11, Pointer<Double > ut12) {
		return iauTtut1(tt1, tt2, dt, Pointer.getPeer(ut11), Pointer.getPeer(ut12));
	}
	protected native static int iauTtut1(double tt1, double tt2, double dt, @Ptr long ut11, @Ptr long ut12);
	/**
	 * Original signature : <code>int iauUt1tai(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:280</i>
	 */
	public static int iauUt1tai(double ut11, double ut12, double dta, Pointer<Double > tai1, Pointer<Double > tai2) {
		return iauUt1tai(ut11, ut12, dta, Pointer.getPeer(tai1), Pointer.getPeer(tai2));
	}
	protected native static int iauUt1tai(double ut11, double ut12, double dta, @Ptr long tai1, @Ptr long tai2);
	/**
	 * Original signature : <code>int iauUt1tt(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:282</i>
	 */
	public static int iauUt1tt(double ut11, double ut12, double dt, Pointer<Double > tt1, Pointer<Double > tt2) {
		return iauUt1tt(ut11, ut12, dt, Pointer.getPeer(tt1), Pointer.getPeer(tt2));
	}
	protected native static int iauUt1tt(double ut11, double ut12, double dt, @Ptr long tt1, @Ptr long tt2);
	/**
	 * Original signature : <code>int iauUt1utc(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:284</i>
	 */
	public static int iauUt1utc(double ut11, double ut12, double dut1, Pointer<Double > utc1, Pointer<Double > utc2) {
		return iauUt1utc(ut11, ut12, dut1, Pointer.getPeer(utc1), Pointer.getPeer(utc2));
	}
	protected native static int iauUt1utc(double ut11, double ut12, double dut1, @Ptr long utc1, @Ptr long utc2);
	/**
	 * Original signature : <code>int iauUtctai(double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:286</i>
	 */
	public static int iauUtctai(double utc1, double utc2, Pointer<Double > tai1, Pointer<Double > tai2) {
		return iauUtctai(utc1, utc2, Pointer.getPeer(tai1), Pointer.getPeer(tai2));
	}
	protected native static int iauUtctai(double utc1, double utc2, @Ptr long tai1, @Ptr long tai2);
	/**
	 * Original signature : <code>int iauUtcut1(double, double, double, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:288</i>
	 */
	public static int iauUtcut1(double utc1, double utc2, double dut1, Pointer<Double > ut11, Pointer<Double > ut12) {
		return iauUtcut1(utc1, utc2, dut1, Pointer.getPeer(ut11), Pointer.getPeer(ut12));
	}
	protected native static int iauUtcut1(double utc1, double utc2, double dut1, @Ptr long ut11, @Ptr long ut12);
	/**
	 * VectorMatrix/AngleOps<br>
	 * Original signature : <code>void iauA2af(int, double, char*, int[4])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:293</i>
	 */
	public static void iauA2af(int ndp, double angle, Pointer<Byte > sign, Pointer<Integer > idmsf) {
		iauA2af(ndp, angle, Pointer.getPeer(sign), Pointer.getPeer(idmsf));
	}
	protected native static void iauA2af(int ndp, double angle, @Ptr long sign, @Ptr long idmsf);
	/**
	 * Original signature : <code>void iauA2tf(int, double, char*, int[4])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:295</i>
	 */
	public static void iauA2tf(int ndp, double angle, Pointer<Byte > sign, Pointer<Integer > ihmsf) {
		iauA2tf(ndp, angle, Pointer.getPeer(sign), Pointer.getPeer(ihmsf));
	}
	protected native static void iauA2tf(int ndp, double angle, @Ptr long sign, @Ptr long ihmsf);
	/**
	 * Original signature : <code>int iauAf2a(char, int, int, double, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:297</i>
	 */
	public static int iauAf2a(byte s, int ideg, int iamin, double asec, Pointer<Double > rad) {
		return iauAf2a(s, ideg, iamin, asec, Pointer.getPeer(rad));
	}
	protected native static int iauAf2a(byte s, int ideg, int iamin, double asec, @Ptr long rad);
	/**
	 * Original signature : <code>double iauAnp(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:299</i>
	 */
	native public static double iauAnp(double a);
	/**
	 * Original signature : <code>double iauAnpm(double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:301</i>
	 */
	native public static double iauAnpm(double a);
	/**
	 * Original signature : <code>void iauD2tf(int, double, char*, int[4])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:303</i>
	 */
	public static void iauD2tf(int ndp, double days, Pointer<Byte > sign, Pointer<Integer > ihmsf) {
		iauD2tf(ndp, days, Pointer.getPeer(sign), Pointer.getPeer(ihmsf));
	}
	protected native static void iauD2tf(int ndp, double days, @Ptr long sign, @Ptr long ihmsf);
	/**
	 * Original signature : <code>int iauTf2a(char, int, int, double, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:305</i>
	 */
	public static int iauTf2a(byte s, int ihour, int imin, double sec, Pointer<Double > rad) {
		return iauTf2a(s, ihour, imin, sec, Pointer.getPeer(rad));
	}
	protected native static int iauTf2a(byte s, int ihour, int imin, double sec, @Ptr long rad);
	/**
	 * Original signature : <code>int iauTf2d(char, int, int, double, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:307</i>
	 */
	public static int iauTf2d(byte s, int ihour, int imin, double sec, Pointer<Double > days) {
		return iauTf2d(s, ihour, imin, sec, Pointer.getPeer(days));
	}
	protected native static int iauTf2d(byte s, int ihour, int imin, double sec, @Ptr long days);
	/**
	 * VectorMatrix/BuildRotations<br>
	 * Original signature : <code>void iauRx(double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:312</i>
	 */
	public static void iauRx(double phi, Pointer<Double > r) {
		iauRx(phi, Pointer.getPeer(r));
	}
	protected native static void iauRx(double phi, @Ptr long r);
	/**
	 * Original signature : <code>void iauRy(double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:314</i>
	 */
	public static void iauRy(double theta, Pointer<Double > r) {
		iauRy(theta, Pointer.getPeer(r));
	}
	protected native static void iauRy(double theta, @Ptr long r);
	/**
	 * Original signature : <code>void iauRz(double, double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:316</i>
	 */
	public static void iauRz(double psi, Pointer<Double > r) {
		iauRz(psi, Pointer.getPeer(r));
	}
	protected native static void iauRz(double psi, @Ptr long r);
	/**
	 * VectorMatrix/CopyExtendExtract<br>
	 * Original signature : <code>void iauCp(double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:321</i>
	 */
	public static void iauCp(Pointer<Double > p, Pointer<Double > c) {
		iauCp(Pointer.getPeer(p), Pointer.getPeer(c));
	}
	protected native static void iauCp(@Ptr long p, @Ptr long c);
	/**
	 * Original signature : <code>void iauCpv(double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:323</i>
	 */
	public static void iauCpv(Pointer<Double > pv, Pointer<Double > c) {
		iauCpv(Pointer.getPeer(pv), Pointer.getPeer(c));
	}
	protected native static void iauCpv(@Ptr long pv, @Ptr long c);
	/**
	 * Original signature : <code>void iauCr(double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:325</i>
	 */
	public static void iauCr(Pointer<Double > r, Pointer<Double > c) {
		iauCr(Pointer.getPeer(r), Pointer.getPeer(c));
	}
	protected native static void iauCr(@Ptr long r, @Ptr long c);
	/**
	 * Original signature : <code>void iauP2pv(double[3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:327</i>
	 */
	public static void iauP2pv(Pointer<Double > p, Pointer<Double > pv) {
		iauP2pv(Pointer.getPeer(p), Pointer.getPeer(pv));
	}
	protected native static void iauP2pv(@Ptr long p, @Ptr long pv);
	/**
	 * Original signature : <code>void iauPv2p(double[2][3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:329</i>
	 */
	public static void iauPv2p(Pointer<Double > pv, Pointer<Double > p) {
		iauPv2p(Pointer.getPeer(pv), Pointer.getPeer(p));
	}
	protected native static void iauPv2p(@Ptr long pv, @Ptr long p);
	/**
	 * VectorMatrix/Initialization<br>
	 * Original signature : <code>void iauIr(double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:334</i>
	 */
	public static void iauIr(Pointer<Double > r) {
		iauIr(Pointer.getPeer(r));
	}
	protected native static void iauIr(@Ptr long r);
	/**
	 * Original signature : <code>void iauZp(double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:336</i>
	 */
	public static void iauZp(Pointer<Double > p) {
		iauZp(Pointer.getPeer(p));
	}
	protected native static void iauZp(@Ptr long p);
	/**
	 * Original signature : <code>void iauZpv(double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:338</i>
	 */
	public static void iauZpv(Pointer<Double > pv) {
		iauZpv(Pointer.getPeer(pv));
	}
	protected native static void iauZpv(@Ptr long pv);
	/**
	 * Original signature : <code>void iauZr(double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:340</i>
	 */
	public static void iauZr(Pointer<Double > r) {
		iauZr(Pointer.getPeer(r));
	}
	protected native static void iauZr(@Ptr long r);
	/**
	 * VectorMatrix/MatrixOps<br>
	 * Original signature : <code>void iauRxr(double[3][3], double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:345</i>
	 */
	public static void iauRxr(Pointer<Double > a, Pointer<Double > b, Pointer<Double > atb) {
		iauRxr(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(atb));
	}
	protected native static void iauRxr(@Ptr long a, @Ptr long b, @Ptr long atb);
	/**
	 * Original signature : <code>void iauTr(double[3][3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:347</i>
	 */
	public static void iauTr(Pointer<Double > r, Pointer<Double > rt) {
		iauTr(Pointer.getPeer(r), Pointer.getPeer(rt));
	}
	protected native static void iauTr(@Ptr long r, @Ptr long rt);
	/**
	 * VectorMatrix/MatrixVectorProducts<br>
	 * Original signature : <code>void iauRxp(double[3][3], double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:352</i>
	 */
	public static void iauRxp(Pointer<Double > r, Pointer<Double > p, Pointer<Double > rp) {
		iauRxp(Pointer.getPeer(r), Pointer.getPeer(p), Pointer.getPeer(rp));
	}
	protected native static void iauRxp(@Ptr long r, @Ptr long p, @Ptr long rp);
	/**
	 * Original signature : <code>void iauRxpv(double[3][3], double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:354</i>
	 */
	public static void iauRxpv(Pointer<Double > r, Pointer<Double > pv, Pointer<Double > rpv) {
		iauRxpv(Pointer.getPeer(r), Pointer.getPeer(pv), Pointer.getPeer(rpv));
	}
	protected native static void iauRxpv(@Ptr long r, @Ptr long pv, @Ptr long rpv);
	/**
	 * Original signature : <code>void iauTrxp(double[3][3], double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:356</i>
	 */
	public static void iauTrxp(Pointer<Double > r, Pointer<Double > p, Pointer<Double > trp) {
		iauTrxp(Pointer.getPeer(r), Pointer.getPeer(p), Pointer.getPeer(trp));
	}
	protected native static void iauTrxp(@Ptr long r, @Ptr long p, @Ptr long trp);
	/**
	 * Original signature : <code>void iauTrxpv(double[3][3], double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:358</i>
	 */
	public static void iauTrxpv(Pointer<Double > r, Pointer<Double > pv, Pointer<Double > trpv) {
		iauTrxpv(Pointer.getPeer(r), Pointer.getPeer(pv), Pointer.getPeer(trpv));
	}
	protected native static void iauTrxpv(@Ptr long r, @Ptr long pv, @Ptr long trpv);
	/**
	 * VectorMatrix/RotationVectors<br>
	 * Original signature : <code>void iauRm2v(double[3][3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:363</i>
	 */
	public static void iauRm2v(Pointer<Double > r, Pointer<Double > w) {
		iauRm2v(Pointer.getPeer(r), Pointer.getPeer(w));
	}
	protected native static void iauRm2v(@Ptr long r, @Ptr long w);
	/**
	 * Original signature : <code>void iauRv2m(double[3], double[3][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:365</i>
	 */
	public static void iauRv2m(Pointer<Double > w, Pointer<Double > r) {
		iauRv2m(Pointer.getPeer(w), Pointer.getPeer(r));
	}
	protected native static void iauRv2m(@Ptr long w, @Ptr long r);
	/**
	 * VectorMatrix/SeparationAndAngle<br>
	 * Original signature : <code>double iauPap(double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:370</i>
	 */
	public static double iauPap(Pointer<Double > a, Pointer<Double > b) {
		return iauPap(Pointer.getPeer(a), Pointer.getPeer(b));
	}
	protected native static double iauPap(@Ptr long a, @Ptr long b);
	/**
	 * Original signature : <code>double iauPas(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:372</i>
	 */
	native public static double iauPas(double al, double ap, double bl, double bp);
	/**
	 * Original signature : <code>double iauSepp(double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:374</i>
	 */
	public static double iauSepp(Pointer<Double > a, Pointer<Double > b) {
		return iauSepp(Pointer.getPeer(a), Pointer.getPeer(b));
	}
	protected native static double iauSepp(@Ptr long a, @Ptr long b);
	/**
	 * Original signature : <code>double iauSeps(double, double, double, double)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:376</i>
	 */
	native public static double iauSeps(double al, double ap, double bl, double bp);
	/**
	 * VectorMatrix/SphericalCartesian<br>
	 * Original signature : <code>void iauC2s(double[3], double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:381</i>
	 */
	public static void iauC2s(Pointer<Double > p, Pointer<Double > theta, Pointer<Double > phi) {
		iauC2s(Pointer.getPeer(p), Pointer.getPeer(theta), Pointer.getPeer(phi));
	}
	protected native static void iauC2s(@Ptr long p, @Ptr long theta, @Ptr long phi);
	/**
	 * Original signature : <code>void iauP2s(double[3], double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:383</i>
	 */
	public static void iauP2s(Pointer<Double > p, Pointer<Double > theta, Pointer<Double > phi, Pointer<Double > r) {
		iauP2s(Pointer.getPeer(p), Pointer.getPeer(theta), Pointer.getPeer(phi), Pointer.getPeer(r));
	}
	protected native static void iauP2s(@Ptr long p, @Ptr long theta, @Ptr long phi, @Ptr long r);
	/**
	 * Original signature : <code>void iauPv2s(double[2][3], double*, double*, double*, double*, double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:385</i>
	 */
	public static void iauPv2s(Pointer<Double > pv, Pointer<Double > theta, Pointer<Double > phi, Pointer<Double > r, Pointer<Double > td, Pointer<Double > pd, Pointer<Double > rd) {
		iauPv2s(Pointer.getPeer(pv), Pointer.getPeer(theta), Pointer.getPeer(phi), Pointer.getPeer(r), Pointer.getPeer(td), Pointer.getPeer(pd), Pointer.getPeer(rd));
	}
	protected native static void iauPv2s(@Ptr long pv, @Ptr long theta, @Ptr long phi, @Ptr long r, @Ptr long td, @Ptr long pd, @Ptr long rd);
	/**
	 * Original signature : <code>void iauS2c(double, double, double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:387</i>
	 */
	public static void iauS2c(double theta, double phi, Pointer<Double > c) {
		iauS2c(theta, phi, Pointer.getPeer(c));
	}
	protected native static void iauS2c(double theta, double phi, @Ptr long c);
	/**
	 * Original signature : <code>void iauS2p(double, double, double, double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:389</i>
	 */
	public static void iauS2p(double theta, double phi, double r, Pointer<Double > p) {
		iauS2p(theta, phi, r, Pointer.getPeer(p));
	}
	protected native static void iauS2p(double theta, double phi, double r, @Ptr long p);
	/**
	 * Original signature : <code>void iauS2pv(double, double, double, double, double, double, double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:391</i>
	 */
	public static void iauS2pv(double theta, double phi, double r, double td, double pd, double rd, Pointer<Double > pv) {
		iauS2pv(theta, phi, r, td, pd, rd, Pointer.getPeer(pv));
	}
	protected native static void iauS2pv(double theta, double phi, double r, double td, double pd, double rd, @Ptr long pv);
	/**
	 * VectorMatrix/VectorOps<br>
	 * Original signature : <code>double iauPdp(double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:396</i>
	 */
	public static double iauPdp(Pointer<Double > a, Pointer<Double > b) {
		return iauPdp(Pointer.getPeer(a), Pointer.getPeer(b));
	}
	protected native static double iauPdp(@Ptr long a, @Ptr long b);
	/**
	 * Original signature : <code>double iauPm(double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:398</i>
	 */
	public static double iauPm(Pointer<Double > p) {
		return iauPm(Pointer.getPeer(p));
	}
	protected native static double iauPm(@Ptr long p);
	/**
	 * Original signature : <code>void iauPmp(double[3], double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:400</i>
	 */
	public static void iauPmp(Pointer<Double > a, Pointer<Double > b, Pointer<Double > amb) {
		iauPmp(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(amb));
	}
	protected native static void iauPmp(@Ptr long a, @Ptr long b, @Ptr long amb);
	/**
	 * Original signature : <code>void iauPn(double[3], double*, double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:402</i>
	 */
	public static void iauPn(Pointer<Double > p, Pointer<Double > r, Pointer<Double > u) {
		iauPn(Pointer.getPeer(p), Pointer.getPeer(r), Pointer.getPeer(u));
	}
	protected native static void iauPn(@Ptr long p, @Ptr long r, @Ptr long u);
	/**
	 * Original signature : <code>void iauPpp(double[3], double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:404</i>
	 */
	public static void iauPpp(Pointer<Double > a, Pointer<Double > b, Pointer<Double > apb) {
		iauPpp(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(apb));
	}
	protected native static void iauPpp(@Ptr long a, @Ptr long b, @Ptr long apb);
	/**
	 * Original signature : <code>void iauPpsp(double[3], double, double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:406</i>
	 */
	public static void iauPpsp(Pointer<Double > a, double s, Pointer<Double > b, Pointer<Double > apsb) {
		iauPpsp(Pointer.getPeer(a), s, Pointer.getPeer(b), Pointer.getPeer(apsb));
	}
	protected native static void iauPpsp(@Ptr long a, double s, @Ptr long b, @Ptr long apsb);
	/**
	 * Original signature : <code>void iauPvdpv(double[2][3], double[2][3], double[2])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:408</i>
	 */
	public static void iauPvdpv(Pointer<Double > a, Pointer<Double > b, Pointer<Double > adb) {
		iauPvdpv(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(adb));
	}
	protected native static void iauPvdpv(@Ptr long a, @Ptr long b, @Ptr long adb);
	/**
	 * Original signature : <code>void iauPvm(double[2][3], double*, double*)</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:410</i>
	 */
	public static void iauPvm(Pointer<Double > pv, Pointer<Double > r, Pointer<Double > s) {
		iauPvm(Pointer.getPeer(pv), Pointer.getPeer(r), Pointer.getPeer(s));
	}
	protected native static void iauPvm(@Ptr long pv, @Ptr long r, @Ptr long s);
	/**
	 * Original signature : <code>void iauPvmpv(double[2][3], double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:412</i>
	 */
	public static void iauPvmpv(Pointer<Double > a, Pointer<Double > b, Pointer<Double > amb) {
		iauPvmpv(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(amb));
	}
	protected native static void iauPvmpv(@Ptr long a, @Ptr long b, @Ptr long amb);
	/**
	 * Original signature : <code>void iauPvppv(double[2][3], double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:414</i>
	 */
	public static void iauPvppv(Pointer<Double > a, Pointer<Double > b, Pointer<Double > apb) {
		iauPvppv(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(apb));
	}
	protected native static void iauPvppv(@Ptr long a, @Ptr long b, @Ptr long apb);
	/**
	 * Original signature : <code>void iauPvu(double, double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:416</i>
	 */
	public static void iauPvu(double dt, Pointer<Double > pv, Pointer<Double > upv) {
		iauPvu(dt, Pointer.getPeer(pv), Pointer.getPeer(upv));
	}
	protected native static void iauPvu(double dt, @Ptr long pv, @Ptr long upv);
	/**
	 * Original signature : <code>void iauPvup(double, double[2][3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:418</i>
	 */
	public static void iauPvup(double dt, Pointer<Double > pv, Pointer<Double > p) {
		iauPvup(dt, Pointer.getPeer(pv), Pointer.getPeer(p));
	}
	protected native static void iauPvup(double dt, @Ptr long pv, @Ptr long p);
	/**
	 * Original signature : <code>void iauPvxpv(double[2][3], double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:420</i>
	 */
	public static void iauPvxpv(Pointer<Double > a, Pointer<Double > b, Pointer<Double > axb) {
		iauPvxpv(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(axb));
	}
	protected native static void iauPvxpv(@Ptr long a, @Ptr long b, @Ptr long axb);
	/**
	 * Original signature : <code>void iauPxp(double[3], double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:422</i>
	 */
	public static void iauPxp(Pointer<Double > a, Pointer<Double > b, Pointer<Double > axb) {
		iauPxp(Pointer.getPeer(a), Pointer.getPeer(b), Pointer.getPeer(axb));
	}
	protected native static void iauPxp(@Ptr long a, @Ptr long b, @Ptr long axb);
	/**
	 * Original signature : <code>void iauS2xpv(double, double, double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:424</i>
	 */
	public static void iauS2xpv(double s1, double s2, Pointer<Double > pv, Pointer<Double > spv) {
		iauS2xpv(s1, s2, Pointer.getPeer(pv), Pointer.getPeer(spv));
	}
	protected native static void iauS2xpv(double s1, double s2, @Ptr long pv, @Ptr long spv);
	/**
	 * Original signature : <code>void iauSxp(double, double[3], double[3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:426</i>
	 */
	public static void iauSxp(double s, Pointer<Double > p, Pointer<Double > sp) {
		iauSxp(s, Pointer.getPeer(p), Pointer.getPeer(sp));
	}
	protected native static void iauSxp(double s, @Ptr long p, @Ptr long sp);
	/**
	 * Original signature : <code>void iauSxpv(double, double[2][3], double[2][3])</code><br>
	 * <i>native declaration : src\main\cpp\sofa\src\sofa.h:428</i>
	 */
	public static void iauSxpv(double s, Pointer<Double > pv, Pointer<Double > spv) {
		iauSxpv(s, Pointer.getPeer(pv), Pointer.getPeer(spv));
	}
	protected native static void iauSxpv(double s, @Ptr long pv, @Ptr long spv);
}
